<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Platforms>AnyCPU;x64</Platforms>
	<UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="AssemblyInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="appsettings.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="AssemblyInfo.cs">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SimCineCapture.Capture\SimCineCapture.Capture.csproj" />
    <ProjectReference Include="..\SimCineCapture.Core\SimCineCapture.Core.csproj" />
    <ProjectReference Include="..\SimCineCapture.SimConnect\SimCineCapture.SimConnect.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="ViewModels\" />
    <Folder Include="Views\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.5" />
  </ItemGroup>
	
  <ItemGroup>
  <Reference Include="Microsoft.FlightSimulator.SimConnect">
    <HintPath>..\SimCineCapture.SimConnect\3rdparty\Microsoft.FlightSimulator.SimConnect.dll</HintPath>
    <Private>true</Private>
    <SpecificVersion>false</SpecificVersion>
  </Reference>
</ItemGroup>

<ItemGroup>
  <None Include="C:\MSFS SDK\SimConnect SDK\lib\SimConnect.dll">
    <Link>SimConnect.dll</Link>
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </None>
</ItemGroup>

</Project>
